### ISSUE TITLE
Make getGpsDateTime() method unrestricted or just describe why is that so?

### ISSUE THREAD

**Issue by MayMih** [ddyos/UnicodeExifInterface#1]
Method `getGpsDateTime()` must not be restricted to `Scope.LIBRARY` as it is in the original Android's ExifInterFace class.
Why did you restrict it?
Can I use it in my code?

**Comment by ddyos** [comment]
This lib is base on Version "androidx.exifinterface:exifinterface:1.2.1".
I did not restrict that method. It is from google's original source code. 

If you use it in code, you should test the code carefully.

BTW: Method getGpsDateTime() is not be restricted since Version "androidx.exifinterface:exifinterface:1.3.0-alpha01".
